---
- name: Install dependencies (Ubuntu / Debian)
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - unzip
    - libwww-perl
    - libdatetime-perl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install dependencies (CentOS / Red Hat Enterprise Linux)
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - perl-Switch
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
    - perl-Digest-SHA
    - zip
    - unzip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Download cloudwatch monitoring scipts
  get_url:
    url: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-{{ cw_version }}.zip
    dest: /tmp/CloudWatchMonitoringScripts.zip

- name: Setup installation directory
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Unzip cloudwatch monitoring scripts
  unarchive:
    src: /tmp/CloudWatchMonitoringScripts.zip
    dest: "{{ install_dir }}"

- name: Basic check
  command: "ls {{ install_dir }}/aws-scripts-mon"

- name: Set cron job
  cron:
    job: "{{ install_dir }}/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"
    minute: "*/5"
